CREATE DATABASE PizzaDB;
GO

CREATE SCHEMA Pizza;
GO

DROP TABLE Pizza.Users;
CREATE TABLE Pizza.Users
(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL
);

CREATE TABLE Pizza.Transactions
(
	OrderId INT IDENTITY(10,10) NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES Pizza.TransactionOrder(Id),
	UserId INT NOT NULL FOREIGN KEY REFERENCES Pizza.Users(Id),
	StoreId INT NOT NULL FOREIGN KEY REFERENCES Pizza.Store(StoreId),
	OrderTime datetime2 NOT NULL
);

DROP TABLE Pizza.TransactionOrder;
CREATE TABLE Pizza.TransactionOrder
(
	Id INT IDENTITY(10,10) NOT NULL PRIMARY KEY,
	Size NVARCHAR(50) NOT NULL,
	Topping1 NVARCHAR(50) NULL,
	Topping2 NVARCHAR(50) NULL,
	Topping3 NVARCHAR(50) NULL,
	Topping4 NVARCHAR(50) NULL,
	Topping5 NVARCHAR(50) NULL,
	Cost MONEY NOT NULL
);

CREATE TABLE Pizza.Store
(
	StoreId INT IDENTITY(100,100) NOT NULL PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	InventoryId INT NOT NULL FOREIGN KEY REFERENCES Pizza.Inventory(Id)
);

DROP TABLE Pizza.Inventory;
CREATE TABLE Pizza.Inventory
(
	Id INT IDENTITY(100,100) NOT NULL PRIMARY KEY,
	IngredientName NVARCHAR(100) NOT NULL,
	Stock INT NULL,
	Price MONEY
);

GO

-- input basic data here
